apiVersion: v1
kind: ConfigMap
metadata:
  name: dailysync-config
  namespace: dailysync
data:
  NODE_ENV: "production"
  API_PORT: "3001"
  WEB_PORT: "3000"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "dailysync"
---
apiVersion: v1
kind: Secret
metadata:
  name: dailysync-secrets
  namespace: dailysync
type: Opaque
stringData:
  DATABASE_URL: "postgresql://dailysync_user:CHANGE_ME@postgres-service:5432/dailysync"
  JWT_SECRET: "CHANGE_ME_JWT_SECRET"
  NEXTAUTH_SECRET: "CHANGE_ME_NEXTAUTH_SECRET"
  WEBHOOK_API_KEY: "CHANGE_ME_WEBHOOK_KEY"
  POSTGRES_PASSWORD: "CHANGE_ME_DB_PASSWORD"
